#!/bin/bash
set -e
usage="$0 <source> <compiler> <checked c tools> <compiler args> <outputfile>"

if [ -z $1 ] 
then
  echo $usage
  exit 1
fi

if [ -z $2 ] 
then
  echo $usage
  exit 1
fi

if [ -z $3 ]
then
  echo $usage 
  exit 1
fi

if [ -z $4 ]
then
  echo $usage 
  exit 1
fi

if [ -z $5 ] 
then
  echo $usage
  exit 1
fi

src=$1
fullsrc=$(python3 -c "import os; print(os.path.abspath('$src'))")
compiler=$2
tools=$3
args=$4
output=$5


base=$(dirname $fullsrc)
python3 $tools/utils/port_tools/expand_macros.py $compiler $fullsrc tempout $base $args
dune exec -- src/main.exe -f $fullsrc > $output
