#!/bin/bash
# set -o xtrace
# set -e
usage="$0 <basedir> <source> <compiler> <checked c tools> <args>"

if [ -z $1 ] 
then
  echo $usage
  exit 1
fi

if [ -z $2 ] 
then
  echo $usage
  exit 1
fi

if [ -z $3 ]
then
  echo $usage 
  exit 1
fi

if [ -z $4 ]
then
  echo $usage 
  exit 1
fi

if [ -z $5 ] 
then
  echo $usage
  exit 1
fi

# base=$(realpath $1)
base=$1
src=$2
compiler=$3
tools=$4
args=$5
python3 $tools/utils/port_tools/expand_macros.py $compiler $src tempout $base $args
dune exec -- src/main.exe -f $base/$src
