#!/bin/bash
# set -o xtrace
# set -e
usage="$0 <file>"

# if [ $# -lt 4 ] 
# then
#  echo $usage
#  exit 1
# fi

# base=$1
# src=$2
# compiler=$3
# tools=$4
# shift
# shift
# shift
# shift
# args=$*
# python3 $tools/utils/port_tools/expand_macros.py $compiler $src tempout $base $args

dune exec -- src/main.exe -f $1
