SOURCES = assign.c hcg.c maze.c vcg.c channel.c main.c option.c
HDRS = assign.h hcg.h option.h vcg.h channel.h maze.h types.h
PROG = yacr2

RUN_OPTIONS += ./input2.in
OUTPUT = OUT

C3 = ../../../_build/default/src/main.exe
CFLAGS = -I.. -DTODD

include ../../Makefile.common
