PROG     = power
SOURCES = build.c compute.c main.c
HDRS = power.h

CFLAGS = -DTORONTO
LDFLAGS  = -lm
C3 = ../../../_build/default/src/main.exe

FP_TOLERANCE = 0.00001
OUTPUT = power.reference_output

include ../../Makefile.common

