PROG = parson
SOURCES = tests.c parson.c
HDRS = parson.h

CFLAGS = -O0 -g -Wall -Wextra -std=c99 -pedantic-errors
LDFLAGS =
C3 = ../../_build/default/src/main.exe

OUTPUT = OUT

include ../Makefile.common
